[package]
name = "nft-pawnshop"
version = "0.1.0"
authors = ["Bryan Wee"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "3.1.0"
near-contract-standards = "3.1.1"

[dev-dependencies]
near-sdk-sim = "3.2.0"